["AFK Stages"]
Attempts = 2
Formations = 10
"Skip Manual Formations" = false
"Run Manual Formations Last" = false
"Spend Gold" = false
"Start with current Formation" = false
"Suggested Formations" = true

["Arcane Labyrinth"]
Difficulty = 13
"Key Quota" = 2700

["Claim AFK Rewards"]
"Claim Stage Rewards" = false

["Custom Routine 1"]
"Display Name" = "Push Stages"
Repeat = true
"Task List" = ["Season AFK Stages", "AFK Stages", "Claim AFK Rewards", "Equip new Equipment"]

["Custom Routine 2"]
"Display Name" = ""
Repeat = true
"Task List" = []

["Custom Routine 3"]
"Display Name" = ""
Repeat = true
"Task List" = []

[Dailies]
"Claim Daily Rewards" = true
"Mystical House" = true
"Single Pull" = false
"Dream Realm" = true
"Arena Battle" = false
"Claim Friend/Mail/Quest Rewards" = true
"Collect Affinity" = true
"Run Dura's Trials" = true
"AFK Stages" = true
"Buy Discount Affinity" = true
"Buy All Affinity" = false
"Buy Temporal Essences" = false
"Essence Buy Count" = 1
"Run Legend Trials" = true

["Dream Realm"]
"Spend Gold" = false

["Guild Manager Scan"]
"Guild Members API URL" = "https://clcozchimagtnzohuvsk.supabase.co/rest/v1/guild_states?id=eq.citadel-chqp&select=state&apikey=sb_publishable_LVK-OqTDRQ572wbfDaMqDQ_-7xxdv6n"
"Days to Scan" = 1
"Scan Supreme Arena" = true
"Scan Guild Activeness" = false
"Scan DR Today on Sunday" = false
"Debug OCR Output" = true
"Scan AFK Stages Rankings" = false
"AFK Stage Phases to Scan" = 1
"Ignore Day Restrictions" = false
"Use Qwen2-VL (GPU)" = false
"Confirm Qwen2-VL Download (~2.2 GB)" = false

["Dura's Trials"]
Attempts = 5
Formations = 10
"Spend Gold" = false
"Start with current Formation" = true
"Suggested Formations" = true
"Skip Manual Formations" = false
"Run Manual Formations Last" = true

[General]
"Assist Limit" = 20
"Exclude Heroes" = []
"OCR Engine" = "Tesseract"

["Legend Trial"]
Attempts = 5
Formations = 10
"Skip Manual Formations" = false
"Spend Gold" = false
"Start with current Formation" = true
"Suggested Formations" = true
"Run Manual Formations Last" = true
Towers = [
    "Lightbearer",
    "Wilder",
    "Graveborn",
    "Mauler",
]

["Titan Reaver Proxy Battles"]
"Titan Reaver Proxy Battle Limit" = 50

["Ravaged Realm"]
Squads = ["Lightbearer", "Wilder", "Graveborn", "Mauler"]
Attempts = 5
"Suggested Formations" = true
"Spend Gold" = false

[Homestead]
"Craft Item Limit" = 80

["Supreme Arena"]
Attempts = 5
"Opponent Position" = "Left"
